apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-check-deployment
  labels:
    app: uptime-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-check
  template:
    metadata:
      labels:
        app: uptime-check
    spec:
      containers:
      - name: uptime-check
        image: deepak275/prometheus-sample
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100M
          limits:
            cpu: 600m
            memory: 500M
