branches:
  only:
  - master
language: python
python: 3.7
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coverage coveralls
script: coverage run --source=. -m unittest discover -v -s . -p "test*.py"
after_success:
  - coveralls
