apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mapi-dr
  namespace: mapi
spec:
  host: mapi-app-sit.mapi.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 0
      # http:
      #   http2MaxRequests: 1000
      #   maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 1m