apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  generation: 1
  name: common-is-app-lb
  namespace: supporting
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: common-is-app-lb
status:
  currentHealthy: 1
  desiredHealthy: 1
  disruptionsAllowed: 0
  expectedPods: 1
  observedGeneration: 1
